//
// Generated file, do not edit! Created by nedtool 5.5 from src/messagetype/TraceGenerateMessage.msg.
//

#ifndef __TRACEGENERATEMESSAGE_M_H
#define __TRACEGENERATEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/messagetype/TraceGenerateMessage.msg:17</tt> by nedtool.
 * <pre>
 * message TraceGenerateMessage
 * {
 *     int packetSize;
 *     int64_t frameSequenceID;
 * }
 * </pre>
 */
class TraceGenerateMessage : public ::omnetpp::cMessage
{
  protected:
    int packetSize;
    int64_t frameSequenceID;

  private:
    void copy(const TraceGenerateMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TraceGenerateMessage&);

  public:
    TraceGenerateMessage(const char *name=nullptr, short kind=0);
    TraceGenerateMessage(const TraceGenerateMessage& other);
    virtual ~TraceGenerateMessage();
    TraceGenerateMessage& operator=(const TraceGenerateMessage& other);
    virtual TraceGenerateMessage *dup() const override {return new TraceGenerateMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPacketSize() const;
    virtual void setPacketSize(int packetSize);
    virtual int64_t getFrameSequenceID() const;
    virtual void setFrameSequenceID(int64_t frameSequenceID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TraceGenerateMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TraceGenerateMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TRACEGENERATEMESSAGE_M_H

